name: Build backend server
env:
  IMAGE: ghcr.io/${{ github.repository }}/server:latest
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:server"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE }}
